name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag, with v prefix'
        required: true

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: Checkout Source
        uses: actions/checkout@v4

      # 2. 设置 Java 环境 (Android 编译强制要求)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          


      # 3. 设置 PNPM/NODE 环境
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # 或者使用 latest
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # 4. 安装依赖
      - name: Install Dependencies
        run: pnpm install

      # 5. 安装 Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 6. 构建 Web 应用
      - name: Build web app
        run: pnpm build
        env:
          VITE_APP_VERSION: ${{ github.ref_name }}

      # 7. 添加 Android 平台
      - name: Add Android platform
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi

      # 8. 同步 Capacitor
      - name: Capacitor Sync
        run: npx cap sync android

      # 9. 构建 Android
      - name: Build Android
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease


      #  对 APK 进行签名
      - uses: ilharp/sign-android-release@v2 # Or use @nightly
        name: Sign app APK
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 36.0.0

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: github.event.inputs.tag != '' || startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.sign_app.outputs.signedReleaseFile }}
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: Release ${{ github.event.inputs.tag || github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
